### PR TITLE
Fixed getRandomString() bug

### LINKED ISSUE #1: getRandomString() only iterates through elements 0-31 in blah

### PR DESCRIPTION
**Pull request by msavich**
Closes #1 
Want to iterate through elements 0-40, because blah's length is 41

### CODE REVIEW

File: sqlinject.cpp [hunk 1]
```diff
@@ -22,7 +22,7 @@ std::string getRandomString() {
     char blah[] = "0987654321qwertyuiopzxcvbnmlhgfdsazxcvbnm";
     std::stringstream ss;
     for( int i=0; i<SIZE; i++ ) {
-       ss << blah[ std::rand() % (SIZE - 1) ];
+       ss << blah[ std::rand() % (strlen(blah) - 1) ];
```
Comment (stevejarvis) [inline sqlinject.cpp]: Thanks for the contribution. You're right this is an issue, but there's still a bug I believe. We really wanna grab an index in `std::rand() % strlen(blah)`. Using a modulo 1 less than the length of the array will prevent us from ever choosing the last element. In other words, the range of `rand % x-1` is `[0, x-2]`. The right answer is `rand % x` and a range of `[0, x-1]`.

File: sqlinject.cpp [hunk 2]
```diff
@@ -22,7 +22,7 @@ std::string getRandomString() {
     char blah[] = "0987654321qwertyuiopzxcvbnmlhgfdsazxcvbnm";
     std::stringstream ss;
     for( int i=0; i<SIZE; i++ ) {
-       ss << blah[ std::rand() % (SIZE - 1) ];
+       ss << blah[ std::rand() % strlen(blah) ];
```
Comment (stevejarvis) [inline sqlinject.cpp]: Cool, I don't think this compiles though. Believe the `string` import needs to change to `string.h` for the std C header (which includes `strlen`). I'm using GCC 6.2 toolchain.

**Comment by msavich** [comment]
Whoops, yeah it seems like I forgot that. I included `<cstring>` since this is a c++ program.
